# Generated by Django 4.2.5 on 2023-11-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_email_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
