# Generated by Django 4.2.5 on 2023-10-31 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_ejemplares_estado_remove_ejemplares_libro_and_more'),
        ('usuario', '0002_alter_informeusuario_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplares',
            fields=[
                ('id_ejemplar', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('numero_ejemplar', models.IntegerField()),
                ('resumen', models.CharField(max_length=1000)),
                ('compuesto', models.CharField(max_length=20)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('fecha_iniprestamo', models.DateField(blank=True, null=True)),
                ('fecha_finprestamo', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('id_ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.ejemplares')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
