# Generated by Django 4.2.5 on 2023-11-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplares',
            name='numero_ejemplar',
        ),
    ]
