# Generated by Django 4.2.5 on 2023-11-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_remove_ejemplares_numero_ejemplar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='id_ejemplar',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_ejemplares',
            field=models.CharField(default='vacio', max_length=4000),
        ),
    ]
