# Generated by Django 4.2.5 on 2023-11-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_remove_prestamo_id_ejemplar_prestamo_id_ejemplares'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoEstado',
            fields=[
                ('id_prestado', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('prestado', models.CharField(default='invalido', max_length=80)),
            ],
        ),
    ]
