# Generated by Django 4.2.5 on 2023-11-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamoestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='prestado_estado',
            field=models.ForeignKey(default='En espera', on_delete=django.db.models.deletion.CASCADE, to='prestamos.prestamoestado'),
        ),
    ]
