# Generated by Django 4.2.5 on 2023-10-31 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplares',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ejemplares',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='id_ejemplar',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='id_usuario',
        ),
    ]
